### PR TITLE
Directory Structure cleanup and tests

### PR DESCRIPTION
**Pull request by antotocar34**
Cleaned up the directory structure.

Added a single test that tests if smc procedure correctly finds the correct model for 
`beta_true = [0, 0, 0, 0, 1]`.

Changed `numpy.f` to `np.f`.

Added setup.py file to make sure `python -m pytest` works as intended.

The developer simply needs to run `python setup.py develop` for things to be set up.

### CODE REVIEW

**Review by maxim-fedotov — COMMENTED** [review]
Well, sometimes using non-abbreviated names is more preferrable since it improves code readability, but at a cost of reducing clarity.

**Comment by maxim-fedotov** [comment]
Regarding  .get part. May be it could be better to have either

model_seen = bool(self.computed_at.get(model_id))

or more readable option

model_seen = True if self.computed_at.get(model_id, None) else False

**Comment by maxim-fedotov** [comment]
In total, great job, thanks!

**Comment by antotocar34** [comment]
> Regarding .get part. May be it could be better to have either
> 
> model_seen = bool(self.computed_at.get(model_id))
> 
> or more readable option
> 
> model_seen = True if self.computed_at.get(model_id, None) else False

The problem with both is that `bool(0)` returns `False`.

**Comment by antotocar34** [comment]
> Well, sometimes using non-abbreviated names is more preferrable since it improves code readability, but at a cost of reducing clarity.

With regards to clarity, `import numpy as np` is pretty common thing in the data science / ML python community as far as I can tell.

**Comment by maxim-fedotov** [comment]
> > Well, sometimes using non-abbreviated names is more preferrable since it improves code readability, but at a cost of reducing clarity.
> 
> With regards to clarity, `import numpy as np` is pretty common thing in the data science / ML python community as far as I can tell.

As you prefer, not really important for me. Although in the docstrings we still have to change it to the full name since it is a bad practice to write abbreviated names in the documentation.

**Comment by maxim-fedotov** [comment]
> > Regarding .get part. May be it could be better to have either
> > model_seen = bool(self.computed_at.get(model_id))
> > or more readable option
> > model_seen = True if self.computed_at.get(model_id, None) else False
> 
> The problem with both is that `bool(0)` returns `False`.

But we do not explore this model. Yep, this is a weak part now, should figure out how do we work with this model.

**Pull request merged**
